export const STORE_CATEGORIES = [
  "Automotive",
  "Baby & Kids",
  "Business",
  "Computers & Software",
  "Education",
  "Health & Fitness",
  "Home & Garden",
  "Sports & Outdoors",
  "Technology",
  "Travel",
  "Women's Fashion",
  "Men's Fashion",
  "Electronics",
  "Food & Drink",
  "Beauty",
  "Pets",
  "Jewelry",
  "Office",
  "Entertainment",
  "Gifts & Flowers",
  "Pharmacy",
  "Other",
] as const;
